apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80  # The port the service will expose
      targetPort: 5000  # The port the container listens on
  type: ClusterIP  # Use ClusterIP or NodePort for internal access only
