apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  MYSQL_HOST: "mysql-service.default.svc.cluster.local"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "password"
  MYSQL_DATABASE: "test_db"
